"""Mood and voice presets for story pipeline."""

MOOD_PRESETS = {
    "dramatic":   {"voice": "dramatic",    "rate": "-25%"},
    "tension":    {"voice": "tension",     "rate": "-20%"},
    "intense":    {"voice": "intense",     "rate": "-10%"},
    "dark":       {"voice": "dark",        "rate": "-30%"},
    "warm":       {"voice": "warm",        "rate": "-25%"},
    "caring":     {"voice": "caring",      "rate": "-25%"},
    "storyteller": {"voice": "storyteller", "rate": "-20%"},
    "friendly":   {"voice": "friendly",    "rate": "-15%"},
    "cheerful":   {"voice": "cheerful",    "rate": "-10%"},
    "news":       {"voice": "news",        "rate": "-10%"},
    "documentary": {"voice": "documentary", "rate": "-15%"},
    "narrator":   {"voice": "narrator",    "rate": "-15%"},
    "tiktok":     {"voice": "tiktok",      "rate": "-5%"},
    "viral":      {"voice": "viral",       "rate": "-5%"},
    "cute":       {"voice": "cute",        "rate": "-10%"},
    "whisper":    {"voice": "warm",        "rate": "-35%"},
    "slow":       {"voice": "warm",        "rate": "-40%"},
    "fast":       {"voice": "warm",        "rate": "+10%"},
    "angry":      {"voice": "intense",     "rate": "+5%"},
    "sad":        {"voice": "caring",      "rate": "-30%"},
    "calm":       {"voice": "warm",        "rate": "-30%"},
    "excited":    {"voice": "viral",       "rate": "+5%"},
}

VOICE_MUSIC_MAP = {
    "dramatic": "dark cinematic dramatic",
    "tension": "suspenseful dark ambient",
    "intense": "intense action epic",
    "dark": "dark horror ambient",
    "storyteller": "inspiring storytelling background",
    "warm": "warm acoustic gentle",
    "caring": "emotional piano soft",
    "friendly": "happy upbeat background",
    "cheerful": "cheerful positive pop",
    "news": "news corporate background",
    "documentary": "cinematic documentary epic",
    "narrator": "epic cinematic orchestral",
    "tiktok": "trending tiktok beat",
    "viral": "energetic viral beat",
    "cute": "cute playful fun",
    "male-id": "Indonesian gamelan ambient",
    "female-id": "Indonesian ambient soft",
}
